### ISSUE TITLE
Fatal Error detected whith par2cmdline under Linux Mint Jammy

### ISSUE THREAD

**Issue by zwiebus** [Tensai75/nxg-upper#1]
As can be seen in the debug log, a fatal error is output after starting par2cmdline.
Tested versions :
v1.1.0: par2cmdline-turbo 
v0.8.1: par2cmdline
The error occurs with both versions.

Par2 itself works perfectly in both versions.

Debuglog:
17:25:16 INFO:    NxG Upper v0.0.0-beta-4
17:25:16 DEBUG:   Total data size: 2928981 Bytes
17:25:16 DEBUG:   Temp path set to: /home/zwiebus/Downloads/nzb/nxg/nxg-tmp/4D25G1rYs2IC199OHUzdb
17:25:16 INFO:    Starting rar process
17:25:16 DEBUG:   Rar volume size: 0 Bytes
17:25:16 DEBUG:   Rar command: /usr/bin/rar a -o+ -idcd -ep1 -r -m0 -hpgcnctm6x4Dd4bK4q1Bi3MErTT /home/zwiebus/Downloads/nzb/nxg/nxg-tmp/4D25G1rYs2IC199OHUzdb/4D25G1rYs2IC199OHUzdb.rar /home/zwiebus/Downloads/upload/testcbdchdch/*
17:25:16 DEBUG:   RAR: Creating archive /home/zwiebus/Downloads/nzb/nxg/nxg-tmp/4D25G1rYs2IC199OHUzdb/4D25G1rYs2IC199OHUzdb.rar
17:25:16 INFO:    Creation of rar archives successful
17:25:16 DEBUG:   Par block size: 768000 Bytes
17:25:16 INFO:    Starting par process
17:25:16 DEBUG:   Deleting par2 files
17:25:16 DEBUG:   Files to delete: []
17:25:16 DEBUG:   Par command: /usr/bin/par2 create -l -s768000 -r10 /home/zwiebus/Downloads/nzb/nxg/nxg-tmp/4D25G1rYs2IC199OHUzdb/4D25G1rYs2IC199OHUzdb /home/zwiebus/Downloads/nzb/nxg/nxg-tmp/4D25G1rYs2IC199OHUzdb/*.*
17:25:16 INFO:    Fatal Error detected
17:25:16 INFO:    Cancelling upload
17:25:16 INFO:    Deleting temporary folder "/home/zwiebus/Downloads/nzb/nxg/nxg-tmp/4D25G1rYs2IC199OHUzdb"
17:25:16 ERROR:   exit status 3

**Comment by Tensai75** [comment]
Fixed with e010e823b173088ecc2829eb6ebb433c4bd0a3dc. 
Thanks for reporting.
